name: Terraform CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-format-and-validate:
    name: Check Terraform Formatting and Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt 

      - name: Terraform Validate
        run: terraform validate
